/**
 *
 * $Id$
 */
package Gemma.validation;

import Gemma.ElementoExpresion;
import Gemma.TipoOperador;

/**
 * A sample validator interface for {@link Gemma.ExpresionBinaria}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpresionBinariaValidator {
	boolean validate();

	boolean validateExpresionIzquierda(ElementoExpresion value);
	boolean validateExpresionDerecha(ElementoExpresion value);
	boolean validateOperador(TipoOperador value);
}
