/**
 *
 * $Id$
 */
package Gemma.validation;

import Gemma.MacroOm;
import Gemma.Transicion;
import Gemma.VariableGemma;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Gemma.Gemma}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GemmaValidator {
	boolean validate();

	boolean validateMacroOms(EList<MacroOm> value);
	boolean validateTransiciones(EList<Transicion> value);
	boolean validateVariablesGemma(EList<VariableGemma> value);
}
